language: "node_js"
node_js:
  - '5'
  - '4'
sudo: false
before_install:
  - "npm config set spin false"
  - "npm install -g npm"
env:
  - DEPLOY_VERSION=testing
script: "npm test"
notifications:
  email: false
